### ISSUE TITLE
tensorboard error

### ISSUE THREAD

**Issue by ipproo** [botaoye/OSTrack#57]
when i run this:python tracking/create_default_local_file.py --workspace_dir . --data_dir ./data --save_dir ./output

i get that error:
Traceback (most recent call last):
  File "/home/pc_3270/OSTrack/tracking/create_default_local_file.py", line 4, in <module>
    from lib.train.admin import create_default_local_file_ITP_train
  File "/home/pc_3270/OSTrack/tracking/../lib/train/__init__.py", line 1, in <module>
    from .admin.multigpu import MultiGPU
  File "/home/pc_3270/OSTrack/tracking/../lib/train/admin/__init__.py", line 3, in <module>
    from .tensorboard import TensorboardWriter
  File "/home/pc_3270/OSTrack/tracking/../lib/train/admin/tensorboard.py", line 7, in <module>
    from tensorboardX import SummaryWriter
ModuleNotFoundError: No module named 'tensorboardX'

**Comment by botaoye** [comment]
you can install tensorboardX by `pip install tensorboardX`
