### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by Alexandic** [botaoye/OSTrack#96]
Traceback (most recent call last):
  File "lib/train/run_training.py", line 109, in <module>
    main()
  File "lib/train/run_training.py", line 101, in main
    run_training(args.script, args.config, cudnn_benchmark=args.cudnn_benchmark,
  File "lib/train/run_training.py", line 75, in run_training
    expr_func(settings)
  File "/workspace/OSTrack-main/lib/train/../../lib/train/train_script.py", line 48, in run
    loader_train, loader_val = build_dataloaders(cfg, settings)
  File "/workspace/OSTrack-main/lib/train/../../lib/train/base_functions.py", line 124, in build_dataloaders
    dataset_train = sampler.TrackingSampler(datasets=names2datasets(cfg.DATA.TRAIN.DATASETS_NAME, settings, opencv_loader),
  File "/workspace/OSTrack-main/lib/train/../../lib/train/base_functions.py", line 44, in names2datasets
    datasets.append(Got10k(settings.env.got10k_dir, split='vottrain', image_loader=image_loader))
  File "/workspace/OSTrack-main/lib/train/../../lib/train/dataset/got10k.py", line 67, in __init__
    self.sequence_list = [self.sequence_list[i] for i in seq_ids]
  File "/workspace/OSTrack-main/lib/train/../../lib/train/dataset/got10k.py", line 67, in <listcomp>
    self.sequence_list = [self.sequence_list[i] for i in seq_ids]
IndexError: list index out of range

**Comment by jryxxx** [comment]
i have the same question

**Comment by LuBoqi** [comment]
I have the same question, too.
